C++ SS (CPU part)
epfl-radio-astro/pypeline pull request #36
Opened 2022-06-07 22:06 UTC by orliac

Porting the standard synthesizer to C++
(Note: to be reviewed by Simon but not available from the Reviewers pane)

2022-06-09 08:08 UTC, AdhocMan requested changes

2022-06-09 08:08 UTC, AdhocMan commented on src/bluebild/src/host/standard_synthesizer_host.cpp
> +void cluster_layers(const T*  __restrict__ unlayered_stats,
These functions seem to be used only in this cpp file. So using `static` or an a unnamed namespace would be better.

2022-06-09 08:08 UTC, AdhocMan commented on src/bluebild/src/standard_synthesizer.cpp
> +    template <typename T>
Indentation seems to inconsistent here.

2022-06-09 08:08 UTC, AdhocMan commented on src/bluebild/src/standard_synthesizer.cpp
> +            //FILL_ME
I'd suggest throwing an `NotImplementedError` here.

2022-06-13 06:28 UTC, orliac commented on pypeline/phased_array/bluebild/field_synthesizer/spatial_domain.py
> +import nvtx
Removed for now

2022-06-13 06:31 UTC, orliac commented on src/bluebild/CMakeLists.txt
> +if(DEFINED ENV{CMAKE_BUILD_TYPE})
I now rely on -DCMAKE_BUILD_TYPE and not on environment variables anymore to tune the compilation options
(Note: we are on CMake 3.16 at EPFL)

2022-06-13 06:31 UTC, orliac commented on src/bluebild/CMakeLists.txt
> +option(BLUEBILD_BUILD_TESTS "Build tests" ON)
Leftover from testing, set back to OFF

2022-06-13 06:33 UTC, orliac commented on src/bluebild/CMakeLists.txt
> +if(DEFINED ENV{MARLA_ROOT})
I've added a FindMarla.cmake package

2022-06-13 06:35 UTC, orliac commented on src/bluebild/include/bluebild/bluebild.hpp
> +    //template <typename T, typename = std::enable_if_t<std::is_same_v<T, double> ||
Type restriction back in. I had to fix an issue to make it work (a missing template argument in pybluebild.cpp)

2022-06-13 06:36 UTC, orliac commented on src/bluebild/python/pybluebild.cpp
> +    standard_synthesizer(ctx,
All inputs are now checked for dimensions

2022-06-13 06:36 UTC, orliac commented on src/bluebild/src/CMakeLists.txt
> +    target_link_libraries(bluebild PUBLIC OpenMP::OpenMP_CXX)
Done

2022-06-13 06:37 UTC, orliac commented on src/bluebild/src/bluebild_export.h
> +
Sorry, this was a mistake, I removed the file

2022-06-13 06:37 UTC, orliac commented on src/bluebild/src/host/standard_synthesizer_host.cpp
> +void cluster_layers(const T*  __restrict__ unlayered_stats,
Done

2022-06-13 06:37 UTC, orliac commented on src/bluebild/src/standard_synthesizer.cpp
> +    template <typename T>
Indentation corrected

2022-06-15 07:44 UTC, AdhocMan approved these changes
Looks good to me now.
Only one suggestion:
Store the test data in a compact json format (without line breaks and spaces), to keep the repository size in check. Definitively starting to notice long checkout times and you can at least half the size of these json files. Maybe at some point, we will have to think about a compressed file format.

2022-07-19 07:57 UTC, closed without merging